Refactor Github action workflows to handle errors
The Python checks in the Github action workflow for mypy and pydocstyle have been updated to capture their respective exit codes. An additional step has been included to observe and react to those exit codes, terminating the workflow with a failure status if any errors are detected in either of the checks.

diff --git a/.github/workflows/python_checks.yml b/.github/workflows/python_checks.yml
--- a/.github/workflows/python_checks.yml
+++ b/.github/workflows/python_checks.yml
@@ -32,13 +32,21 @@ jobs:
       run: |
         echo "MODIFIED_FILES=$(git diff --name-only refs/remotes/origin/${{ github.base_ref }} $(git merge-base refs/remotes/origin/${{ github.base_ref }} refs/remotes/origin/${{ github.head_ref }}) | grep '\.py$')" >> $GITHUB_ENV
 
-    - name: Run mypy and save output
+    - name: Run mypy
       if: env.MODIFIED_FILES != ''
       run: |
         echo "${{ env.MODIFIED_FILES }}" | xargs mypy --ignore-missing-imports --disallow-untyped-defs 
+        echo "mypy_exit_code=$?" >> $GITHUB_ENV
 
-    - name: Run pydocstyle and save output
+    - name: Run pydocstyle
       if: env.MODIFIED_FILES != ''
       run: |
-        echo "${{ env.MODIFIED_FILES }}" | xargs pydocstyle 
+        echo "${{ env.MODIFIED_FILES }}" | xargs pydocstyle
+        echo "pydocstyle_exit_code=$?" >> $GITHUB_ENV
 
+    - name: Check errors
+      run: |
+        if [ "$mypy_exit_code" != "0" ] || [ "$pydocstyle_exit_code" != "0" ]; then
+          echo "Errors detected in mypy or pydocstyle"
+          exit 1
+        fi
